export default {
    ImageClipHoverCards: "ImageClipHoverCards",
    DepthOfFieldCards: "DepthOfFieldCards",
    DirectionAwareCards: "DirectionAwareCards",
    GameStyleCards: "GameStyleCards",
    CircleReductionServiceCards: "CircleReductionServiceCards",
    SwivelRotationCards: "SwivelRotationCards",
    FlipUpHoverCards: "FlipUpHoverCards",
    IsometricHoverCards: "IsometricHoverCards",
    CircleGrowthServiceCards: "CircleGrowthServiceCards",
    ImageSlideLeftCards: "ImageSlideLeftCards",
    NeumorphismCards: "NeumorphismCards",
    SkewedBorderCards: "SkewedBorderCards",
    GlowingCards: "GlowingCards",
    GreetingCardStyleCards: "GreetingCardStyleCards",
    CircleGrowthIconCards: "CircleGrowthIconCards",
    IconGrowthCards: "IconGrowthCards",
    HoverSwitchCards: "HoverSwitchCards",
}